classDiagram
    class MenuItem {
        +name: str
        +price: float
        +__init__(name: str, price: float)
        +calculate_price() float
    }

    class Beverage {
        +size: str
        +__init__(name: str, price: float, size: str)
    }

    class Appetizer {
        +spicy: bool
        +__init__(name: str, price: float, spicy: bool=False)
    }

    class MainCourse {
        +portion_size: str
        +__init__(name: str, price: float, portion_size: str="regular")
    }

    class Order {
        -items: List~MenuItem~
        +__init__()
        +add_item(item: MenuItem) None
        +calculate_total() float
        +apply_discount() float
    }

    %% Relaciones
    MenuItem <|-- Beverage
    MenuItem <|-- Appetizer
    MenuItem <|-- MainCourse
    Order *-- MenuItem
